import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Menu, X, ArrowUpRight, MapPin, Phone, CalendarDays, Trophy, Shield, ChevronRight } from 'lucide-react';
import { tournamentInfo as info, teams, fixtures, results, standings, champions, gallery } from './data/tournament';
import './styles.css';

const poster = '/assets/tournament-poster.jpeg';
const nav = [['TOURNAMENT','#tournament'],['TEAMS','#teams'],['FIXTURES','#fixtures'],['STANDINGS','#standings'],['BRACKET','#bracket'],['HISTORY','#history'],['VENUE','#venue'],['CONTACT','#contact']];

function App(){
 const [open,setOpen]=useState(false); const [route,setRoute]=useState(location.hash||'#home');
 const go=(h)=>{setRoute(h);location.hash=h;setOpen(false);window.scrollTo({top:0,behavior:'smooth'})};
 const isHome=route==='#home'||!route;
 return <div className="app"><div className="ticker"><span className="live-dot"/> OFFICIAL TOURNAMENT WEBSITE <span className="ticker-detail">GULABI DEVI MEMORIAL CUP · 14TH EDITION · BBIT</span><span className="ticker-right">REGISTRATION OPENS SOON <ArrowUpRight size={14}/></span></div>
 <header className="nav"><button className="brand" onClick={()=>go('#home')}><span className="brand-mark">B</span><span>BBIT <small>FOOTBALL</small></span></button><nav>{nav.map(([n,h])=><button key={h} onClick={()=>go(h)}>{n}</button>)}</nav><button className="register mini" onClick={()=>go('#register')}>REGISTER <ArrowUpRight size={15}/></button><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header>
 {open&&<div className="mobile-menu">{nav.map(([n,h])=><button key={h} onClick={()=>go(h)}>{n}<ChevronRight size={16}/></button>)}<button onClick={()=>go('#register')}>REGISTER <ArrowUpRight size={16}/></button></div>}
 {isHome?<Home go={go}/>:<Page route={route} go={go}/>}<Footer go={go}/></div>
}

function Home({go}){return <>
 <section className="hero"><div className="hero-image"/><div className="hero-grid"/><div className="hero-content"><div className="eyebrow"><span/> BBIT PRESENTS <span/></div><p className="kicker">ANNUAL INTER-COLLEGE CHAMPIONSHIP</p><h1>GULABI DEVI<br/><em>MEMORIAL CUP</em></h1><div className="hero-meta"><b>14<sup>TH</sup></b><span>EDITION</span><i/> <span>LEAGUE-CUM-KNOCKOUT<br/>11-A-SIDE FOOTBALL</span></div><div className="actions"><button className="register" onClick={()=>go('#register')}>REGISTER YOUR TEAM <ArrowUpRight size={18}/></button><button className="ghost" onClick={()=>go('#tournament')}>EXPLORE TOURNAMENT <ChevronRight size={17}/></button></div></div><div className="hero-side"><span>EST. BBIT</span><div className="vertical-line"/><span>14 / 26</span></div><div className="hero-bottom"><div><small>TOURNAMENT DATE</small><strong>COMING SOON</strong></div><div><small>VENUE</small><strong>BBIT FOOTBALL GROUND</strong></div><div><small>ENTRY FEE</small><strong>₹{info.entryFee.toLocaleString('en-IN')} <span>PER TEAM</span></strong></div></div></section>
 <section className="status-strip"><div className="status-icon"><CalendarDays size={22}/></div><div><small>THE ROAD TO GLORY BEGINS</small><h3>Tournament date coming soon</h3></div><div className="status-note">Stay tuned for fixtures, team announcements<br/>and registration updates.</div><button className="text-link" onClick={()=>go('#contact')}>GET UPDATES <ArrowUpRight size={16}/></button></section>
 <section className="intro section" id="tournament"><div className="section-label">01 / THE TOURNAMENT</div><div className="intro-grid"><div><h2>MORE THAN<br/><span>A TOURNAMENT.</span></h2></div><div className="intro-copy"><p>An annual inter-college football championship bringing together talented footballers, competitive college teams and passionate supporters for a celebration of the beautiful game.</p><button className="text-link" onClick={()=>go('#history')}>DISCOVER THE LEGACY <ArrowUpRight size={16}/></button></div></div><div className="stat-row"><Stat value="14" label="EDITIONS"/><Stat value="01" label="TROPHY"/><Stat value="11" label="A-SIDE FOOTBALL"/><Stat value="∞" label="STORIES TO TELL"/></div></section>
 <section className="details section"><div className="section-label">02 / THE ESSENTIALS</div><div className="detail-heading"><h2>BUILT FOR<br/><span>THE BIG STAGE.</span></h2><p>Everything you need to know. More details will be added as the tournament takes shape.</p></div><div className="info-grid"><Info title="FORMAT" value={info.format}/><Info title="MATCH TYPE" value={info.matchType}/><Info title="VENUE" value={info.venue}/><Info title="DATE" value="Coming Soon" accent/></div></section>
 <section className="feature section" id="fixtures"><div className="section-label">03 / MATCH CENTRE</div><div className="feature-head"><h2>THE ACTION<br/><span>STARTS SOON.</span></h2><button className="outline" onClick={()=>go('#fixtures')}>VIEW ALL FIXTURES <ArrowUpRight size={16}/></button></div><Empty title="Fixtures will be announced soon." text="The match centre will come alive when the draw is confirmed." icon={<Trophy/>}/></section>
 <section className="split-section section" id="teams"><div><div className="section-label">04 / THE CONTENDERS</div><h2>WHO WILL<br/><span>RISE?</span></h2><p>College teams from across the region will battle for their place in the history of the Gulabi Devi Memorial Cup.</p><button className="text-link" onClick={()=>go('#teams')}>MEET THE TEAMS <ArrowUpRight size={16}/></button></div><div className="poster-frame"><img src={poster} alt="Gulabi Devi Memorial Cup official tournament poster"/><div className="frame-tag">OFFICIAL<br/>POSTER / 2026</div></div></section>
 <section className="legacy section" id="history"><div className="legacy-word">LEGACY</div><div className="section-label">05 / THE LEGACY</div><h2>14 EDITIONS.<br/><span>ONE TROPHY.</span></h2><p>Countless stories are waiting to be written. Explore the journey of a tournament built on competition, community and the love of football.</p><button className="outline" onClick={()=>go('#history')}>EXPLORE HISTORY <ArrowUpRight size={16}/></button></section>
 <Venue go={go}/><Registration go={go}/><Contact go={go}/>
 </>}

 const Stat=({value,label})=><div className="stat"><strong>{value}</strong><span>{label}</span></div>; const Info=({title,value,accent})=><div className={'info '+(accent?'accent':'')}><small>{title}</small><strong>{value}</strong></div>;
 function Empty({title,text,icon}){return <div className="empty"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
 function Venue({go}){return <section className="venue section" id="venue"><div className="venue-map"><div className="map-grid"/><MapPin size={30}/><span>BBIT<br/>FOOTBALL GROUND</span></div><div className="venue-copy"><div className="section-label">06 / THE VENUE</div><h2>WHERE THE<br/><span>GAME LIVES.</span></h2><p>{info.address}</p><button className="text-link" onClick={()=>window.open('https://maps.google.com/?q=BBIT+Football+Ground','_blank')}>GET DIRECTIONS <ArrowUpRight size={16}/></button></div></section>}
 function Registration({go}){return <section className="registration section" id="register"><div className="section-label">07 / JOIN THE CUP</div><div><h2>YOUR JOURNEY<br/><span>STARTS HERE.</span></h2><p>Team registration opens soon. Keep an eye on our official channels for the announcement.</p><button className="register" onClick={()=>go('#contact')}>CONTACT TO REGISTER <ArrowUpRight size={18}/></button></div><div className="fee"><small>TEAM REGISTRATION FEE</small><strong>₹{info.entryFee.toLocaleString('en-IN')}</strong><span>Payment details will be shared<br/>when registration opens.</span></div></section>}
 function Contact(){return <section className="contact section" id="contact"><div className="section-label">08 / CONTACT</div><div className="contact-top"><h2>LET'S TALK<br/><span>FOOTBALL.</span></h2><p>Want to participate? Contact the tournament team for registration updates and enquiries.</p></div><div className="contact-list">{info.contacts.map(c=><a href={'tel:'+c.phone} key={c.name}><span><small>{c.name}</small><strong>{c.phone}</strong></span><Phone size={17}/></a>)}</div></section>}
 function Page({route,go}){const title=route==='#teams'?'THE CONTENDERS':route==='#fixtures'?'MATCH CENTRE':route==='#standings'?'LEAGUE TABLE':route==='#bracket'?'TOURNAMENT BRACKET':route==='#history'?'THE LEGACY':route==='#gallery'?'TOURNAMENT GALLERY':route==='#venue'?'THE VENUE':route==='#register'?'YOUR JOURNEY STARTS HERE':'TOURNAMENT'; const empty=route==='#standings'?'Standings will be updated once league matches begin.':route==='#bracket'?'The knockout bracket will appear once the league stage is confirmed.':route==='#gallery'?'Memories from the tournament will appear here.':route==='#teams'?'Teams will be announced soon.':route==='#fixtures'?'Fixtures will be announced soon.':'Champion records will be updated.'; return <main className="page"><div className="page-kicker">GULABI DEVI MEMORIAL CUP / 14TH EDITION</div><h1>{title}</h1><p className="page-lead">Official tournament information from Budge Budge Institute of Technology.</p>{route==='#venue'?<Venue go={go}/>:route==='#register'?<Registration go={go}/>:<Empty title={empty} text="This section is ready for live tournament data and updates." icon={<Shield/>}/>}</main>}
 function Footer({go}){return <footer><div className="footer-brand"><span className="brand-mark">B</span><div><h3>GULABI DEVI<br/><em>MEMORIAL CUP</em></h3><small>14TH EDITION · BBIT</small></div></div><div className="footer-links"><button onClick={()=>go('#tournament')}>TOURNAMENT</button><button onClick={()=>go('#fixtures')}>MATCH CENTRE</button><button onClick={()=>go('#history')}>THE LEGACY</button><button onClick={()=>go('#contact')}>CONTACT</button></div><div className="footer-social"><span>IG</span><span>FB</span><span>YT</span></div><div className="copyright">© 2026 Gulabi Devi Memorial Cup. All rights reserved.<br/>Organized by Budge Budge Institute of Technology.</div></footer>}

createRoot(document.getElementById('root')).render(<App/>);
